language: go

go:
  - "1.10"

go_import_path: github.com/fripSide/HexGo-CI/

before_install:
  - go version

sudo: true

script:
  - rm -rf cache
  - mkdir cache
  - go run main.go -action gen

after_success:
  - cd ./cache
  - git init
#  - git config user.name 'Travis CI'
#  - git config user.email 'travis@travis-ci.com'
  - git add .
  - git commit -m "Travis build: $TRAVIS_BUILD_NUMBER"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/fripSide/fripSide.github.io.git" master:master

